---

x-common: &common
  build:
    target: development
    context: .
    dockerfile: Dockerfile-dev
  image: "cs-wayback-machine:dev"
  volumes:
    - .:/opt/code

services:
  devtools:
    <<: *common
    command: sleep infinity
    ports:
      - "8000:8000"

  app:
    <<: *common
    restart: "no"
    command:
        - uvicorn
        - "cs_wayback_machine.web.main:app"
        - "--host=0.0.0.0"
        - "--port=8000"
    ports:
      - "8000:8000"
